/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.otus;

import com.google.common.base.Splitter;

public class HelloOtus {
    public static void main(String args[]) {
        HelloOtus hello = new HelloOtus();
        hello.testSplitter();
    }

    private void testSplitter() {
        System.out.println(Splitter.on(' ')
                .trimResults()
                .omitEmptyStrings()
                .split("Hello from otus"));
    }
}